export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const FETCH_MOVIES_DETAILS_SUCCESS = "FETCH_MOVIES_DETAILS_SUCCESS";
export const BOOKMARK_MOVIE = "BOOKMARK_MOVIE"
export const SWITCH_THEME = "SWITCH_THEME"
export const FETCH_MOVIE_DETAILS_REQUEST = "FETCH_MOVIE_DETAILS_REQUEST"
export const FETCH_MOVIE_DETAILS_FAILURE = "FETCH_MOVIE_DETAILS_FAILURE"
